### ISSUE TITLE
Graceful shutdown example

### ISSUE THREAD

**Issue by TudorHulban** [atreugo/examples#3]
Hi,
Maybe a graceful shutdown example could be added.
Thank you

**Comment by TudorHulban** [comment]
I saw #56.
Please consider Gin also exposes a graceful example in https://github.com/gin-gonic/examples/blob/master/graceful-shutdown/graceful-shutdown/server.go using "net/http".

**Comment by savsgio** [comment]
Hi @TudorHulban,

In Atreugo, you could activate the graceful shutdown, activating it in the [Config](https://pkg.go.dev/github.com/savsgio/atreugo/v11?tab=doc#Config.GracefulShutdown).

But maybe, it could be added it as an example.

Could you make a PR?? please
