### ISSUE TITLE
How do you set the auto timeout of the websocket?

### ISSUE THREAD

**Issue by StephanieSunshine** [atreugo/examples#7]
https://github.com/atreugo/examples/tree/master/websocket

I'm trying to set the `ws.ReadMessage()` to have a timeout if no data has been received within a certain time frame. Looking at `atreugo.Config`, I found `ReadTimeout`, `WriteTimeout`, and `IdleTimeout`, but all seem to be ignored once a websocket is connected/upgraded. Can you update the example show how to properly include timeouts?

Thanks

**Comment by savsgio** [comment]
Hi @StephanieSunshine,

The atreugo config variables you are referring to, are for "normal" http connections, not for hijacked connections like websockets, etc.

So maybe you need to set the [conn.SetReadDeadline(<time>)](https://pkg.go.dev/github.com/fasthttp/websocket#Conn.SetReadDeadline)?? Because after that time, you want to close de connection or something similiar, right?

**Comment by StephanieSunshine** [comment]
Thank you, I'm not sure if you would like to include this in the example, but that was indeed the right solution.

Updated code in case you would like to include it or someone else has this question: 
```go
	server.GET("/ws", upgrader.Upgrade(func(ws *websocket.Conn) error {
		for {
			ws.SetReadDeadline(time.Now().Add(30 * time.Second))
			mt, message, err := ws.ReadMessage()
			if err != nil {
				return err
			}

			name := ws.UserValue("name").(string)

			log.Printf("User value: %s", name)
			log.Printf("recv: %s", message)

			err = ws.WriteMessage(mt, append(message, " - "+name...))
			if err != nil {
				return err
			}
		}
	}))
```

**Comment by savsgio** [comment]
Hi @StephanieSunshine,

Of course, this could be included in the example. Could you make a PR, please?

Just one thing, `SetReadDeadline` should be called just one time, not in every loop: 
```diff
- for {
-			ws.SetReadDeadline(time.Now().Add(30 * time.Second))

+ ws.SetReadDeadline(time.Now().Add(30 * time.Second))
+ for {
```

**Comment by StephanieSunshine** [comment]
I can do this, I have school this week and after that, I can probably make
something up.
